### ISSUE TITLE
Unable get all the contacts(Sim contacts)

### ISSUE THREAD

**Issue by srkreddykrify** [blainepwnz/AndroidContacts#29]
Am unable to fetch the all the contacts from the device . some contacts are missing .  can u please help me to  sort it ,

**Comment by blainepwnz** [comment]
Please give me the code you are using to get all contacts.
How much contacts are missing?

**Comment by mianaliasjad** [comment]
@blainepwnz I want to comment on it because I also faced this issue. There was some contacts that were not returned from the library when I used:

`List<ContactData> contactDataList = new ContactsGetterBuilder(context)
                .allFields()
                .buildList();`

But i was able to see those contacts in my phonebook.

**Comment by blainepwnz** [comment]
@mianaliasjad can you give me a little more info, version of android, version of library, something special about contacts, which are not returned?
The problem is that library is covered with tests, where I create lots of contacts and check if all fields are available and lots of other checks. So i need to understand, what is happening there, because tests are working fine.

**Comment by mianaliasjad** [comment]
@blainepwnz I will provide you complete info as soon as I get time. It's a great library and I will do my best to keep it up to date :)

Thanks for the effort!
